import { useState } from 'react'
import { DataTable,type Column } from '../common/DataTable'
import { StatusBadge } from '../common/StatusBadge'
import { platforms,platformRegistry } from '../../config/platforms'
import { usePayments } from '../../hooks/useManagementQueries'
import type { PaymentStatus,PlatformId,Transaction } from '../../types/models'
import { formatDate,formatMoney } from '../../utils/format'
import { SectionError } from '../common/SectionState'
const columns:Column<Transaction>[]=[{key:'id',label:'Transaction ID',render:t=><strong>{t.id}</strong>},{key:'entity',label:'User / merchant',render:t=>t.entityName??t.entityId??'—'},{key:'platform',label:'Platform',render:t=>platformRegistry[t.platform].name},{key:'amount',label:'Amount',render:t=>formatMoney(t.amount)},{key:'method',label:'Method',render:t=>t.paymentMethod??'—'},{key:'status',label:'Status',render:t=><StatusBadge status={t.status}/>},{key:'date',label:'Date',render:t=>formatDate(t.createdAt,true)}]
export function PaymentsTable(){const[page,setPage]=useState(1);const[platform,setPlatform]=useState<PlatformId|undefined>();const[status,setStatus]=useState<PaymentStatus|undefined>();const[currency,setCurrency]=useState('');const q=usePayments({page,limit:10,platform,status,currency:currency||undefined});return <><div className="filter-bar filter-bar--compact"><select value={platform??''} onChange={e=>{setPlatform((e.target.value||undefined) as PlatformId|undefined);setPage(1)}}><option value="">All platforms</option>{platforms.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select><select value={status??''} onChange={e=>{setStatus((e.target.value||undefined) as PaymentStatus|undefined);setPage(1)}}><option value="">All statuses</option><option value="successful">Successful</option><option value="pending">Pending</option><option value="failed">Failed</option><option value="reversed">Reversed / refunded</option><option value="cancelled">Cancelled</option></select><select value={currency} onChange={e=>{setCurrency(e.target.value);setPage(1)}}><option value="">All currencies</option><option>KES</option><option>USD</option></select></div>{q.isError?<SectionError message={q.error.message} onRetry={()=>void q.refetch()}/>:<DataTable columns={columns} data={q.data?.data} loading={q.isLoading} page={q.data?.meta.page} totalPages={q.data?.meta.totalPages} onPageChange={setPage} emptyTitle="No payments match these filters"/>}</>}
