import { Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts'
import { platformRegistry } from '../../config/platforms'
import type { GrowthSeries,PlatformSummary } from '../../types/models'
import { EmptyState } from '../common/SectionState'
import { formatMoney,formatNumber } from '../../utils/format'

export function DistributionChart({platforms,metric='users'}:{platforms:PlatformSummary[];metric?:'users'|'revenue'}) {const data=platforms.map((s)=>({name:platformRegistry[s.platform].name,value:metric==='users'?s.users:s.revenue?.amount,color:platformRegistry[s.platform].color,currency:s.revenue?.currency})).filter((d)=>d.value!==undefined);if(!data.length)return <EmptyState/>;const total=data.reduce((sum,item)=>sum+(item.value??0),0);return <div className="distribution"><div className="chart-box"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="62%" outerRadius="88%" paddingAngle={2}>{data.map((item)=><Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip contentStyle={{background:'#111111',border:'1px solid #222222',borderRadius:6,color:'#D1D5DB'}} formatter={(value)=>metric==='revenue'?formatMoney({amount:Number(value),currency:data[0]?.currency??'KES'}):formatNumber(Number(value))}/></PieChart></ResponsiveContainer><div className="chart-center"><strong>{formatNumber(total,true)}</strong><span>{metric}</span></div></div><div className="chart-legend">{data.map((item)=><div key={item.name}><span className="legend-dot" style={{background:item.color}}/><span>{item.name}</span><strong>{formatNumber(item.value)} <small>{total?`${((item.value??0)/total*100).toFixed(1)}%`:''}</small></strong></div>)}</div></div>}

export function TrendChart({series,valueFormatter=formatNumber}:{series:GrowthSeries[];valueFormatter?:(value:number)=>string}){const allDates=[...new Set(series.flatMap((s)=>s.points.map((p)=>p.date)))];const data=allDates.map((date)=>{const row:Record<string,string|number>={date:new Intl.DateTimeFormat('en',{month:'short',day:'numeric'}).format(new Date(date))};series.forEach((s)=>{const point=s.points.find((p)=>p.date===date);const key=point?.platform??'all';row[key]=point?.value??0});return row});const keys=[...new Set(series.flatMap((s)=>s.points.map((p)=>p.platform??'all')))];if(!data.length)return <EmptyState/>;return <ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:8,right:8,left:-20,bottom:0}}><CartesianGrid stroke="#222222" vertical={false}/><XAxis dataKey="date" tickLine={false} axisLine={false} fontSize={12} stroke="#9CA3AF"/><YAxis tickLine={false} axisLine={false} fontSize={12} stroke="#9CA3AF" tickFormatter={(v)=>formatNumber(v,true)}/><Tooltip contentStyle={{background:'#111111',border:'1px solid #222222',borderRadius:6,color:'#D1D5DB'}} formatter={(v)=>valueFormatter(Number(v))}/><Legend/>{keys.map((key)=><Line key={key} type="monotone" dataKey={key} name={key==='all'?'All platforms':platformRegistry[key as keyof typeof platformRegistry]?.name??key} stroke={key==='all'?'#00ED64':platformRegistry[key as keyof typeof platformRegistry]?.color} strokeWidth={key==='all'?2.5:1.8} dot={false}/>)}</LineChart></ResponsiveContainer>}

export function RevenueBars({platforms}:{platforms:PlatformSummary[]}){const data=platforms.filter((p)=>p.revenue).map((p)=>({name:platformRegistry[p.platform].name,value:p.revenue!.amount,color:platformRegistry[p.platform].color,currency:p.revenue!.currency}));if(!data.length)return <EmptyState/>;return <ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{left:8,right:12}}><CartesianGrid stroke="#222222" horizontal={false}/><XAxis type="number" hide/><YAxis type="category" dataKey="name" width={86} tickLine={false} axisLine={false} fontSize={12} stroke="#9CA3AF"/><Tooltip contentStyle={{background:'#111111',border:'1px solid #222222',borderRadius:6,color:'#D1D5DB'}} formatter={(v)=>formatMoney({amount:Number(v),currency:data[0].currency})}/><Bar dataKey="value" radius={[0,3,3,0]}>{data.map((item)=><Cell key={item.name} fill={item.color}/>)}</Bar></BarChart></ResponsiveContainer>}
