import { useState, type ComponentType } from 'react'
import { NavLink,Outlet } from 'react-router-dom'
import { Activity,BarChart3,Building2,CreditCard,Gauge,HeartPulse,LayoutDashboard,LogOut,Menu,PanelLeftClose,PanelLeftOpen,Settings,TrendingUp,UserRound,WalletCards,X,Zap } from '../common/Icons'
import { platforms } from '../../config/platforms'
import { useAuth } from '../../context/AuthContext'
import type { AdminRole } from '../../types/models'
import { apiModeLabel } from '../../api/client'

type Icon=ComponentType<{size?:number}>
interface NavItem {label:string;to:string;icon:Icon;end?:boolean;roles?:AdminRole[]}
const analyticsRoles:AdminRole[]=['super_admin','admin','viewer']
const primary:NavItem[]=[{label:'Overview',to:'/dashboard',icon:LayoutDashboard,end:true,roles:analyticsRoles}]
const analytics:NavItem[]=[{label:'Users',to:'/users',icon:UserRound,roles:['super_admin','admin','support']},{label:'Revenue',to:'/revenue',icon:WalletCards,roles:['super_admin','admin','finance']},{label:'Growth',to:'/growth',icon:TrendingUp,roles:analyticsRoles}]
const operations:NavItem[]=[{label:'Activity',to:'/activity',icon:Activity,roles:['super_admin','admin','support','viewer']},{label:'Subscriptions',to:'/subscriptions',icon:CreditCard,roles:['super_admin','admin','finance']},{label:'Transactions',to:'/transactions',icon:BarChart3,roles:['super_admin','admin','finance']}]
const payments:NavItem[]=[{label:'Memberships',to:'/memberships',icon:Users,roles:['super_admin','admin','finance']},{label:'Payment analytics',to:'/payments',end:true,icon:WalletCards,roles:['super_admin','admin','finance']},{label:'Payment transactions',to:'/payments/transactions',icon:CreditCard,roles:['super_admin','admin','finance']}]
const system:NavItem[]=[{label:'Platform health',to:'/system',icon:HeartPulse,roles:analyticsRoles},{label:'Settings',to:'/settings',icon:Settings,roles:['super_admin']}]
function Item({item,collapsed,onNavigate}:{item:NavItem;collapsed:boolean;onNavigate:()=>void}){return <NavLink end={item.end} to={item.to} onClick={onNavigate} title={collapsed?item.label:undefined} className={({isActive})=>isActive?'nav-link active':'nav-link'}><item.icon size={17}/><span>{item.label}</span></NavLink>}
export function AppShell(){const[collapsed,setCollapsed]=useState(false);const[mobile,setMobile]=useState(false);const{user,logout}=useAuth();const permitted=(item:NavItem)=>!item.roles||item.roles.includes(user.role);return <div className={`app-shell ${collapsed?'is-collapsed':''}`}><aside className={`sidebar ${mobile?'is-open':''}`}><div className="brand"><span className="brand-mark"><Zap size={19}/></span><div><strong>Vijo</strong><span>Management</span></div><button className="icon-button mobile-close" onClick={()=>setMobile(false)}><X size={20}/></button></div><nav><div className="nav-group">{primary.filter(permitted).map((item)=><Item key={item.to} item={item} collapsed={collapsed} onNavigate={()=>setMobile(false)}/>)}</div><div className="nav-group"><span className="nav-label">Analytics</span>{analytics.filter(permitted).map((item)=><Item key={item.to} item={item} collapsed={collapsed} onNavigate={()=>setMobile(false)}/>)}</div>{analyticsRoles.includes(user.role)&&<div className="nav-group"><span className="nav-label">Platforms</span>{platforms.map((p)=><Item key={p.id} item={{label:p.name,to:p.route,icon:Building2}} collapsed={collapsed} onNavigate={()=>setMobile(false)}/>)}</div>}<div className="nav-group"><span className="nav-label">Payments</span>{payments.filter(permitted).map((item)=><Item key={item.to} item={item} collapsed={collapsed} onNavigate={()=>setMobile(false)}/>)}</div><div className="nav-group"><span className="nav-label">Operations</span>{operations.filter(permitted).map((item)=><Item key={item.to} item={item} collapsed={collapsed} onNavigate={()=>setMobile(false)}/>)}</div><div className="nav-group"><span className="nav-label">System</span>{system.filter(permitted).map((item)=><Item key={item.to} item={item} collapsed={collapsed} onNavigate={()=>setMobile(false)}/>)}</div></nav><div className="sidebar-user"><span>{user.name.slice(0,2).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.role.replace('_',' ')}</small></div><button className="icon-button" onClick={()=>void logout()} aria-label="Sign out"><LogOut size={16}/></button></div></aside>{mobile&&<button className="sidebar-backdrop" onClick={()=>setMobile(false)} aria-label="Close navigation"/>}<div className="app-main"><header className="topbar"><button className="icon-button desktop-toggle" onClick={()=>setCollapsed(!collapsed)} aria-label="Toggle sidebar">{collapsed?<PanelLeftOpen size={19}/>:<PanelLeftClose size={19}/>}</button><button className="icon-button mobile-toggle" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="environment"><span/>Management API <b>{apiModeLabel}</b></div><div className="topbar-title"><Gauge size={16}/>Command center</div></header><main className="content"><Outlet/></main></div></div>}
