import { useParams } from 'react-router-dom'
import { Activity,CreditCard,DollarSign,RefreshCw,TrendingUp,Users } from '../components/common/Icons'
import { PageHeader } from '../components/common/PageHeader'
import { DateRangeFilter } from '../components/dashboard/DateRangeFilter'
import { MetricCard } from '../components/dashboard/MetricCard'
import { TrendChart } from '../components/charts/AnalyticsCharts'
import { DataTable,type Column } from '../components/common/DataTable'
import { SectionError,SectionLoading } from '../components/common/SectionState'
import { StatusBadge } from '../components/common/StatusBadge'
import { isPlatformId,platformRegistry } from '../config/platforms'
import { useDateRange } from '../context/DateRangeContext'
import { usePlatform } from '../hooks/useManagementQueries'
import type { Transaction,UnifiedUser } from '../types/models'
import { formatDate,formatMoney,formatNumber,formatRelativeTime } from '../utils/format'
const userCols:Column<UnifiedUser>[]=[{key:'user',label:'User',render:u=>u.name??u.email??u.id},{key:'joined',label:'Joined',render:u=>formatDate(u.joinedAt)},{key:'status',label:'Status',render:u=><StatusBadge status={u.status}/>}]
const payCols:Column<Transaction>[]=[{key:'id',label:'Transaction',render:t=>t.id},{key:'entity',label:'User / merchant',render:t=>t.entityName??'—'},{key:'amount',label:'Amount',render:t=>formatMoney(t.amount)},{key:'status',label:'Status',render:t=><StatusBadge status={t.status}/>},{key:'date',label:'Date',render:t=>formatDate(t.createdAt,true)}]
export function PlatformPage(){const{id=''}=useParams();return isPlatformId(id)?<PlatformContent id={id}/>:<SectionError message="This platform is not registered in Vijo Management."/>}
function PlatformContent({id}:{id:Parameters<typeof usePlatform>[0]}){const{range}=useDateRange();const config=platformRegistry[id];const query=usePlatform(id,range);if(query.isLoading)return <SectionLoading rows={8}/>;if(query.isError)return <SectionError message={query.error.message} onRetry={()=>void query.refetch()}/>;const d=query.data;if(!d)return null;const s=d.summary;return <><PageHeader eyebrow="Platform analytics" title={config.name} description={`${config.description} · updated ${formatRelativeTime(s.lastUpdatedAt)}`} actions={<><StatusBadge status={s.status}/><button className="button button--secondary" onClick={()=>void query.refetch()}><RefreshCw size={16}/>Refresh</button><DateRangeFilter/></>}/>{s.error&&<div className="banner banner--warning"><strong>Partial data</strong>{s.error}</div>}<section className="metric-grid metric-grid--six"><MetricCard label="Users" value={formatNumber(s.users)} growth={s.userGrowthPercentage} comparison={range.comparisonLabel} icon={<Users size={17}/>}/><MetricCard label="New users" value={formatNumber(s.newUsers)} detail={range.label} icon={<TrendingUp size={17}/>}/><MetricCard label="Active users" value={formatNumber(s.activeUsers)} icon={<Activity size={17}/>}/><MetricCard label="Paying users" value={formatNumber(s.payingUsers)} icon={<CreditCard size={17}/>}/><MetricCard label="Revenue" value={formatMoney(s.revenue,true)} growth={s.revenueGrowthPercentage} comparison={range.comparisonLabel} icon={<DollarSign size={17}/>}/><MetricCard label="Transactions" value={formatNumber(s.transactions)} icon={<CreditCard size={17}/>}/></section><section className="section"><div className="section-heading"><div><h2>{config.name} operations</h2><p>Platform-specific metrics are isolated to this product module.</p></div></div><div className="custom-metrics">{d.metrics.length?d.metrics.map((m)=><article key={m.key}><span>{m.label}</span><strong>{typeof m.value==='object'?formatMoney(m.value):m.value??'—'}</strong>{m.description&&<small>{m.description}</small>}</article>):<p className="empty-inline">No platform-specific metrics are exposed by the backend.</p>}</div></section>{d.growth.length>0&&<section className="panel"><div className="panel-heading"><h2>Growth trend</h2></div><div className="panel-body trend-height"><TrendChart series={d.growth}/></div></section>}<section className="analytics-grid"><article className="panel"><div className="panel-heading"><h2>Recent users</h2></div><DataTable columns={userCols} data={d.recentUsers} emptyTitle="No recent registrations"/></article><article className="panel"><div className="panel-heading"><h2>Recent payments</h2></div><DataTable columns={payCols} data={d.recentPayments} emptyTitle="No recent payments"/></article></section></>}
